import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SessionBookingActions } from "@/components/SessionBookingActions";
import { ShareCoverImage } from "@/components/ShareCoverImage";
import { StudioMediaWarmup } from "@/components/StudioMediaWarmup";
import { PublicVideoCover } from "@/components/PublicVideoCover";
import { getCachedClassShareContext } from "@/lib/cachedSharePages";
import Link from "next/link";
import { studioClassesPath, studioClassPath } from "@/lib/public-paths";
import { buildClassShareMetadata } from "@/lib/publicShareOg";
import { getVideoPreview } from "@/lib/videoPreview";
import { normalizeStudioSlug } from "@/lib/slug";
import { ui } from "@/lib/ui";
import { createClient } from "@/lib/supabase/server";
import { z } from "zod";

type Props = {
  params: Promise<{ studioSlug: string; classSlug: string }>;
  searchParams: Promise<{ session_id?: string; session?: string }>;
};

export async function generateMetadata({ params }: { params: Promise<{ studioSlug: string; classSlug: string }> }): Promise<Metadata> {
  const { studioSlug, classSlug } = await params;
  return buildClassShareMetadata(studioSlug, classSlug);
}

export default async function PublicClassBookingPage({ params, searchParams }: Props) {
  const { studioSlug: rawStudio, classSlug: rawClass } = await params;
  const sp = await searchParams;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const isSignedIn = Boolean(user);
  const ctx = await getCachedClassShareContext(rawStudio ?? "", rawClass ?? "");
  if (!ctx) notFound();
  const { studio, cls } = ctx;
  const studioPublicSlug = studio.public_slug ?? normalizeStudioSlug(rawStudio ?? "");

  // Resolve requestedSessionId from either ?session=<slug> or ?session_id=<uuid>.
  // Share links generated by the dashboard use the slug form; direct links (e.g.
  // from ops tools) may still use the raw UUID form – both are accepted.
  const uuidOk = z.string().uuid().safeParse(sp.session_id ?? "").success;
  const requestedUuid = uuidOk ? String(sp.session_id) : null;
  const slugLookup =
    sp.session && /^[a-z0-9-]{6,80}$/.test(sp.session)
      ? supabase
          .from("class_sessions")
          .select("id")
          .eq("class_id", cls.id)
          .eq("share_slug", sp.session)
          .maybeSingle()
      : null;

  const sessionsPromise = supabase
    .from("class_sessions")
    .select("id, start_time, spots_left, capacity, guest_price, credits_required, status, location_id, class_title_snapshot, class_description_snapshot, class_image_url_snapshot")
    .eq("class_id", cls.id)
    .eq("status", "scheduled")
    .gte("start_time", new Date().toISOString())
    .order("start_time", { ascending: true });

  const [{ data: sessions }, slugRes] = await Promise.all([
    sessionsPromise,
    slugLookup ?? Promise.resolve({ data: null as { id: string } | null }),
  ]);

  let requestedSessionId: string | null = requestedUuid;
  if (!requestedSessionId && slugRes.data?.id) requestedSessionId = slugRes.data.id;

  const orderedSessions = [...(sessions ?? [])].sort((a, b) => {
    if (!requestedSessionId) return 0;
    if (a.id === requestedSessionId) return -1;
    if (b.id === requestedSessionId) return 1;
    return 0;
  });

  const paymentReady = Boolean((studio as { hitpay_enabled?: boolean | null }).hitpay_enabled);

  const coverSrc = (cls as { image_url?: string | null }).image_url ?? null;
  const videoUrl = (cls as { video_url?: string | null }).video_url ?? null;
  const videoPreview = getVideoPreview(videoUrl ?? "");

  const classSlugPath = (cls as { share_slug?: string | null }).share_slug ?? rawClass;
  let sessionQuery = "";
  if (requestedSessionId) {
    sessionQuery = `?session_id=${requestedSessionId}`;
  } else if (sp.session && /^[a-z0-9-]{6,80}$/.test(sp.session)) {
    sessionQuery = `?session=${encodeURIComponent(sp.session)}`;
  }
  const classSharePath = studioClassPath(studioPublicSlug, classSlugPath, sessionQuery);
  const warmupMediaUrls = Array.from(
    new Set(
      [
        coverSrc,
        videoPreview.thumbnailUrl,
        ...orderedSessions
          .slice(0, 4)
          .map((session) => (session as { class_image_url_snapshot?: string | null }).class_image_url_snapshot ?? coverSrc ?? null),
      ]
        .map((url) => String(url ?? "").trim())
        .filter(Boolean),
    ),
  );

  const isSessionShareView = Boolean(requestedSessionId);
  const listSessions = isSessionShareView
    ? orderedSessions.filter((s) => s.id === requestedSessionId)
    : orderedSessions;

  // ── Single-session share view: two-column hero layout ──
  if (isSessionShareView && listSessions.length === 1) {
    const s = listSessions[0];
    const sessionTitle = (s as { class_title_snapshot?: string | null }).class_title_snapshot?.trim() || cls.title;
    const sessionDescription = (s as { class_description_snapshot?: string | null }).class_description_snapshot?.trim() || cls.description || null;
    const sessionCover = (s as { class_image_url_snapshot?: string | null }).class_image_url_snapshot ?? coverSrc;
    const dt = new Date(s.start_time);
    const weekdayLabel = dt.toLocaleDateString("en-SG", { weekday: "short", timeZone: "Asia/Singapore" });
    const monthLabel = dt.toLocaleDateString("en-SG", { month: "short", timeZone: "Asia/Singapore" });
    const dateLabel = dt.toLocaleDateString("en-SG", {
      weekday: "long",
      month: "long",
      day: "numeric",
      year: "numeric",
      timeZone: "Asia/Singapore",
    });
    const timeLabel = dt.toLocaleTimeString("en-SG", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Singapore" });
    const hasGuestPrice = s.guest_price != null;
    const price = hasGuestPrice ? Number(s.guest_price).toFixed(2) : null;
    const spotsLeft = Number(s.spots_left ?? 0);
    const sessionCapacity =
      Number(
        (s as { capacity?: number | null }).capacity ??
          (cls as { capacity?: number | null }).capacity ??
          0,
      ) || 0;
    const spotsLow = spotsLeft > 0 && spotsLeft <= 3;
    const isFull = spotsLeft === 0;

    return (
      <main className="mx-auto w-full max-w-5xl px-4 pb-20 pt-4 sm:px-6 lg:px-8">
        <Link href={studioClassesPath(studioSlug)} className={ui.link}>← Classes</Link>
        <StudioMediaWarmup urls={warmupMediaUrls} />
        <div className="mt-4 grid grid-cols-1 gap-8 lg:grid-cols-[1fr_380px] lg:items-start lg:gap-12">
          {/* ── Left: class info ── */}
          <div className="min-w-0">
            {videoPreview.embedUrl || (videoUrl && videoUrl.trim()) ? (
              <div className="mb-6">
                <PublicVideoCover
                  title={sessionTitle}
                  coverUrl={sessionCover}
                  embedUrl={videoPreview.embedUrl}
                  fallbackUrl={videoUrl?.trim() || null}
                />
              </div>
            ) : (
              <ShareCoverImage
                src={sessionCover}
                alt={sessionTitle}
                sharePath={classSharePath}
                shareTitle={sessionTitle}
                shareText={`Book ${sessionTitle} at ${studio.name}`}
              />
            )}
            <h1 className={ui.h1}>{sessionTitle}</h1>
            {sessionDescription ? (
              <p className="mt-4 whitespace-pre-wrap leading-relaxed text-stone-700 dark:text-stone-300">
                {sessionDescription}
              </p>
            ) : null}
            {!paymentReady ? (
              <p className={`mt-4 flex items-center gap-1 text-xs ${ui.error}`}>
                Online payment is not configured for this studio.
              </p>
            ) : null}
          </div>

          {/* ── Right: sticky booking card ── */}
          <div className="lg:sticky lg:top-8">
            <div className={`${ui.card} overflow-hidden sm:p-6`}>
              {/* Session summary */}
              <div className="flex items-center gap-4 pb-4">
                <div className="flex w-14 shrink-0 flex-col items-center rounded-xl border border-stone-200 bg-stone-50 py-2 dark:border-stone-700 dark:bg-stone-800">
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-stone-500 dark:text-stone-400">
                    {weekdayLabel}
                  </span>
                  <span className="text-xl font-bold leading-tight text-stone-900 dark:text-stone-50">
                    {dt.getDate()}
                  </span>
                  <span className="text-[10px] text-stone-500 dark:text-stone-400">{monthLabel}</span>
                </div>
                <div className="min-w-0">
                  <p className="font-semibold text-stone-900 dark:text-stone-50">{timeLabel}</p>
                  <p className="mt-0.5 text-sm text-stone-500 dark:text-stone-400">{dateLabel}</p>
                </div>
              </div>

              <div className="flex items-center justify-between border-t border-stone-100 py-3.5 dark:border-stone-800">
                <span className="text-sm text-stone-500 dark:text-stone-400">Per session</span>
                <div className="flex flex-col items-end gap-0.5">
                  {price ? (
                    <span className="text-xl font-bold tabular-nums text-stone-900 dark:text-stone-50">${price}</span>
                  ) : null}
                  {s.credits_required != null && Number(s.credits_required) > 0 ? (
                    <span className="text-xs text-stone-400 dark:text-stone-500">
                      or {Number(s.credits_required)} class pass{Number(s.credits_required) !== 1 ? "es" : ""}
                    </span>
                  ) : null}
                </div>
              </div>

              <div className="flex items-center justify-between border-t border-stone-100 py-3.5 dark:border-stone-800">
                <span className="text-sm text-stone-500 dark:text-stone-400">Availability</span>
                <span
                  className={`text-sm font-semibold ${
                    isFull
                      ? "text-red-600 dark:text-red-400"
                      : spotsLow
                        ? "text-amber-700 dark:text-amber-300"
                        : "text-teal-700 dark:text-teal-300"
                  }`}
                >
                  {isFull
                    ? sessionCapacity > 0
                      ? `Full · 0 / ${sessionCapacity}`
                      : "Full"
                    : sessionCapacity > 0
                      ? `${spotsLeft} / ${sessionCapacity} spots left`
                      : `${spotsLeft} spots left`}
                </span>
              </div>

              {/* Booking form */}
              <div className="border-t border-stone-100 pt-4 dark:border-stone-800">
                {isFull ? (
                  <p className={`text-sm ${ui.muted}`}>This class is full. Please check back for other sessions.</p>
                ) : (
                  <SessionBookingActions
                    slug={studioPublicSlug}
                    sessionId={s.id}
                    guestPrice={Number(s.guest_price ?? 0)}
                    paymentReady={paymentReady}
                    isSignedIn={isSignedIn}
                    creditsRequired={Number(s.credits_required ?? 0)}
                  />
                )}
              </div>
            </div>
          </div>
        </div>
      </main>
    );
  }

  // ── Multi-session / no-session fallback layout ──
  return (
    <main className={ui.page}>
      <Link href={studioClassesPath(studioSlug)} className={ui.link}>← Classes</Link>
      <StudioMediaWarmup urls={warmupMediaUrls} />
      {videoPreview.embedUrl || (videoUrl && videoUrl.trim()) ? (
        <div className="mb-6">
          <PublicVideoCover
            title={cls.title}
            coverUrl={coverSrc}
            embedUrl={videoPreview.embedUrl}
            fallbackUrl={videoUrl?.trim() || null}
          />
        </div>
      ) : (
        <ShareCoverImage
          src={coverSrc}
          alt={cls.title}
          sharePath={classSharePath}
          shareTitle={cls.title}
          shareText={`Book ${cls.title} at ${studio.name}`}
        />
      )}

      <div className="max-w-2xl">
        <h1 className={ui.h1}>{cls.title}</h1>
        {cls.description ? (
          <p className="mt-3 whitespace-pre-wrap leading-relaxed text-stone-700 dark:text-stone-300">
            {cls.description}
          </p>
        ) : null}
        {!paymentReady ? (
          <p className={`mt-2 flex items-center gap-1 text-xs ${ui.error}`}>
            Online payment is not configured for this studio.
          </p>
        ) : null}
      </div>

      {listSessions.length > 0 ? (
        <h2 className={`${ui.h2} mt-10`}>Upcoming sessions</h2>
      ) : null}

      <ul className="mt-4 flex max-w-2xl flex-col gap-4">
        {listSessions.map((s) => {
          const dt = new Date(s.start_time);
          const weekdayLabel = dt.toLocaleDateString("en-SG", { weekday: "short", timeZone: "Asia/Singapore" });
          const monthLabel = dt.toLocaleDateString("en-SG", { month: "short", timeZone: "Asia/Singapore" });
          const timeLabel = dt.toLocaleTimeString("en-SG", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Singapore" });
          const spotsLeft = Number(s.spots_left ?? 0);
          const sessionCapacity =
            Number(
              (s as { capacity?: number | null }).capacity ??
                (cls as { capacity?: number | null }).capacity ??
                0,
            ) || 0;
          const spotsLow = spotsLeft > 0 && spotsLeft <= 3;
          return (
            <li key={s.id} className={ui.card}>
              <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div className="flex items-start gap-3">
                  <div className="flex w-14 shrink-0 flex-col items-center rounded-xl border border-stone-200 bg-stone-50 py-1.5 dark:border-stone-700 dark:bg-stone-800">
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-stone-500 dark:text-stone-400">
                      {weekdayLabel}
                    </span>
                    <span className="text-xl font-bold leading-tight text-stone-900 dark:text-stone-50">
                      {dt.getDate()}
                    </span>
                    <span className="text-[10px] text-stone-500 dark:text-stone-400">{monthLabel}</span>
                  </div>
                  <div className="min-w-0">
                    <p className="font-semibold text-stone-900 dark:text-stone-50">{timeLabel}</p>
                    <div className="mt-2 flex flex-wrap items-baseline gap-1.5">
                      {s.guest_price != null ? (
                        <>
                          <span className="text-base font-bold tabular-nums text-teal-700 dark:text-teal-300">
                            ${Number(s.guest_price).toFixed(2)}
                          </span>
                          <span className={`text-xs ${ui.muted}`}>/ session</span>
                        </>
                      ) : null}
                    </div>
                  </div>
                </div>
                <span
                  className={`mt-0.5 inline-flex w-fit shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${
                    spotsLeft === 0
                      ? "bg-red-50 text-red-600 dark:bg-red-950/40 dark:text-red-400"
                      : spotsLow
                        ? "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300"
                        : "bg-teal-50 text-teal-700 dark:bg-teal-950/40 dark:text-teal-300"
                  }`}
                >
                  {spotsLeft === 0
                    ? sessionCapacity > 0
                      ? `Full · 0 / ${sessionCapacity}`
                      : "Full"
                    : sessionCapacity > 0
                      ? `${spotsLeft} / ${sessionCapacity} spots left`
                      : spotsLow
                        ? `${spotsLeft} spots left`
                        : `${spotsLeft} spots`}
                </span>
              </div>

              <div className="mt-3 border-t border-stone-100 pt-3 dark:border-stone-800 sm:mt-4">
                {spotsLeft === 0 ? (
                  <span className={`text-sm ${ui.muted}`}>This class is full</span>
                ) : (
                  <SessionBookingActions
                    slug={studioPublicSlug}
                    sessionId={s.id}
                    guestPrice={Number(s.guest_price ?? 0)}
                    paymentReady={paymentReady}
                    isSignedIn={isSignedIn}
                    creditsRequired={Number(s.credits_required ?? 0)}
                  />
                )}
              </div>
            </li>
          );
        })}
      </ul>

      {!listSessions.length ? (
        <div className={`mt-6 max-w-2xl ${ui.emptyState}`}>
          <p className={`text-sm ${ui.muted}`}>
            {isSessionShareView
              ? "This session is not available for booking anymore."
              : "No upcoming sessions yet. Check back soon."}
          </p>
        </div>
      ) : null}
    </main>
  );
}
