import Link from "next/link";
import type { Metadata } from "next";
import { Suspense } from "react";
import { notFound } from "next/navigation";
import { BookButton } from "@/components/BookButton";
import { PackageBookButton } from "@/components/PackageBookButton";
import { InlineSignInPanel } from "@/components/InlineSignInPanel";
import { QuickBookPanel } from "@/components/QuickBookPanel";
import { ShareCoverImage } from "@/components/ShareCoverImage";
import { mergeGuestRecordsForUser } from "@/lib/guestMerge";
import {
  hasEligiblePackageForSession,
  sumCreditsInStudio,
  type MemberPackageForCredits,
} from "@/lib/memberCredits";
import { getCachedClassShareContext } from "@/lib/cachedSharePages";
import { getPaynowSummary } from "@/lib/paynow";
import { buildClassShareMetadata } from "@/lib/publicShareOg";
import { normalizeStudioSlug } from "@/lib/slug";
import { ui } from "@/lib/ui";
import { createClient } from "@/lib/supabase/server";
import { z } from "zod";

type Props = {
  params: Promise<{ studioSlug: string; classSlug: string }>;
  searchParams: Promise<{ session_id?: string; session?: string }>;
};

export async function generateMetadata({ params }: { params: Promise<{ studioSlug: string; classSlug: string }> }): Promise<Metadata> {
  const { studioSlug, classSlug } = await params;
  return buildClassShareMetadata(studioSlug, classSlug);
}

export default async function PublicClassBookingPage({ params, searchParams }: Props) {
  const { studioSlug: rawStudio, classSlug: rawClass } = await params;
  const sp = await searchParams;

  const supabase = await createClient();
  const [{ data: { user } }, ctx] = await Promise.all([
    supabase.auth.getUser(),
    getCachedClassShareContext(rawStudio ?? "", rawClass ?? ""),
  ]);
  if (!ctx) notFound();
  const { studio, cls } = ctx;
  const studioPublicSlug = studio.public_slug ?? normalizeStudioSlug(rawStudio ?? "");

  // Resolve requestedSessionId from either ?session=<slug> or ?session_id=<uuid>.
  // Share links generated by the dashboard use the slug form; direct links (e.g.
  // from ops tools) may still use the raw UUID form – both are accepted.
  const uuidOk = z.string().uuid().safeParse(sp.session_id ?? "").success;
  const requestedUuid = uuidOk ? String(sp.session_id) : null;
  const slugLookup =
    sp.session && /^[a-z0-9-]{6,80}$/.test(sp.session)
      ? supabase
          .from("class_sessions")
          .select("id")
          .eq("class_id", cls.id)
          .eq("share_slug", sp.session)
          .maybeSingle()
      : null;

  const sessionsPromise = supabase
    .from("class_sessions")
    .select("id, start_time, spots_left, capacity, guest_price, credits_required, status, location_id")
    .eq("class_id", cls.id)
    .eq("status", "scheduled")
    .gte("start_time", new Date().toISOString())
    .order("start_time", { ascending: true });

  const packsPromise = user
    ? (async () => {
        await mergeGuestRecordsForUser(user.id, user.email);
        const { data: packs } = await supabase
          .from("client_packages")
          .select("id, credits_left, expiry_date, packages!inner(name, studio_id, location_id)")
          .eq("client_id", user.id)
          .eq("packages.studio_id", studio.id)
          .gt("credits_left", 0)
          .or(`expiry_date.is.null,expiry_date.gt.${new Date().toISOString()}`);
        const userPacks = ((packs ?? []) as {
          id: string;
          credits_left: number;
          expiry_date: string | null;
          packages?: { name?: string; studio_id?: string; location_id?: string | null } | null;
        }[]).map((p) => {
          const pkg = Array.isArray(p.packages) ? p.packages[0] : p.packages;
          return {
            id: p.id,
            name: pkg?.name ?? "Package",
            credits_left: p.credits_left,
            expiry_date: p.expiry_date,
            studio_id: pkg?.studio_id ?? studio.id,
            location_id: pkg?.location_id ?? null,
          };
        });
        return { userPacks, packCredits: sumCreditsInStudio(userPacks, studio.id) };
      })()
    : Promise.resolve({ userPacks: [] as MemberPackageForCredits[], packCredits: 0 });

  const [{ data: sessions }, slugRes, packResult] = await Promise.all([
    sessionsPromise,
    slugLookup ?? Promise.resolve({ data: null as { id: string } | null }),
    packsPromise,
  ]);

  let requestedSessionId: string | null = requestedUuid;
  if (!requestedSessionId && slugRes.data?.id) requestedSessionId = slugRes.data.id;

  const { userPacks, packCredits } = packResult;
  const orderedSessions = [...(sessions ?? [])].sort((a, b) => {
    if (!requestedSessionId) return 0;
    if (a.id === requestedSessionId) return -1;
    if (b.id === requestedSessionId) return 1;
    return 0;
  });

  const paynow = getPaynowSummary({
    paynow_enabled: Boolean(studio.paynow_enabled),
    paynow_proxy_type: studio.paynow_proxy_type ?? null,
    paynow_uen: studio.paynow_uen ?? null,
    paynow_mobile: studio.paynow_mobile ?? null,
    paynow_payee_name: studio.paynow_payee_name ?? null,
  });

  const coverSrc = (cls as { image_url?: string | null }).image_url ?? null;

  const classSlugPath = (cls as { share_slug?: string | null }).share_slug ?? rawClass;
  let sessionQuery = "";
  if (requestedSessionId) {
    sessionQuery = `?session_id=${requestedSessionId}`;
  } else if (sp.session && /^[a-z0-9-]{6,80}$/.test(sp.session)) {
    sessionQuery = `?session=${encodeURIComponent(sp.session)}`;
  }
  const classSharePath = `/class/${studioPublicSlug}/${classSlugPath}${sessionQuery}`;

  const isSessionShareView = Boolean(requestedSessionId);
  const listSessions = isSessionShareView
    ? orderedSessions.filter((s) => s.id === requestedSessionId)
    : orderedSessions;

  return (
    <main className={ui.page}>
      {/* ── Hero cover (full-bleed within page padding) ── */}
      <ShareCoverImage
        src={coverSrc}
        alt={cls.title}
        sharePath={classSharePath}
        shareTitle={cls.title}
        shareText={`Book ${cls.title} at ${studio.name}`}
      />

      {/* ── Class header ── */}
      <div className="max-w-2xl">
        <h1 className={ui.h1}>{cls.title}</h1>
        {cls.description ? (
          <p className={`mt-3 whitespace-pre-wrap text-stone-700 dark:text-stone-300`}>{cls.description}</p>
        ) : null}
        {/* Credits / sign-in nudge */}
        {user ? (
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <span className={ui.badge}>{packCredits} credit{packCredits !== 1 ? "s" : ""} available</span>
            <Link href="/checkout" className={`text-sm ${ui.link}`}>Buy more</Link>
          </div>
        ) : (
          <Suspense
            fallback={
              <div className="mt-3 h-10 w-24 animate-pulse rounded-lg bg-stone-100 dark:bg-stone-800" />
            }
          >
            <InlineSignInPanel />
          </Suspense>
        )}

        {!paynow.configured ? (
          <p className={`mt-2 flex items-center gap-1 text-xs ${ui.error}`}>{paynow.line}</p>
        ) : null}
      </div>

      {/* ── Sessions (full list only when this URL is not tied to one session) ── */}
      {!isSessionShareView ? (
        <h2 className={`${ui.h2} mt-10`}>Upcoming sessions</h2>
      ) : null}
      <ul className={`flex max-w-2xl flex-col gap-3 ${isSessionShareView ? "mt-8" : "mt-4"}`}>
        {listSessions.map((s) => {
          const dt = new Date(s.start_time);
          const weekdayLabel = dt.toLocaleDateString("en-SG", { weekday: "short" });
          const monthLabel = dt.toLocaleDateString("en-SG", { month: "short" });
          const timeLabel = dt.toLocaleTimeString("en-SG", { hour: "2-digit", minute: "2-digit" });
          const creditsRequired = Number(s.credits_required ?? 1);
          const sessionCreditCtx = {
            studio_id: studio.id,
            location_id: s.location_id ?? null,
            credits_required: creditsRequired,
          };
          const hasEligiblePack = hasEligiblePackageForSession(userPacks, sessionCreditCtx);
          const spotsLeft = Number(s.spots_left ?? 0);
          const sessionCapacity =
            Number(
              (s as { capacity?: number | null }).capacity ??
                (cls as { capacity?: number | null }).capacity ??
                0,
            ) || 0;
          const spotsLow = spotsLeft > 0 && spotsLeft <= 3;
          const isHighlighted = requestedSessionId === s.id;
          return (
            <li
              key={s.id}
              className={`${ui.card} transition-shadow ${isHighlighted ? "ring-2 ring-teal-400/70 shadow-md shadow-teal-400/10" : ""}`}
            >
              {/* Date + spots row */}
              <div className="flex items-start justify-between gap-3">
                {/* Date block */}
                <div className="flex items-center gap-3">
                  {/* Calendar accent */}
                  <div className="flex w-12 shrink-0 flex-col items-center rounded-xl border border-stone-200 bg-stone-50 py-1 dark:border-stone-700 dark:bg-stone-800">
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-stone-500 dark:text-stone-400">
                      {weekdayLabel}
                    </span>
                    <span className="text-lg font-bold leading-tight text-stone-900 dark:text-stone-50">
                      {dt.getDate()}
                    </span>
                    <span className="text-[10px] text-stone-500 dark:text-stone-400">
                      {monthLabel}
                    </span>
                  </div>
                  {/* Time + price */}
                  <div className="min-w-0">
                    <p className="font-semibold text-stone-900 dark:text-stone-50">{timeLabel}</p>
                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      <span className="inline-flex items-baseline gap-1.5 rounded-lg border border-teal-200 bg-teal-50 px-2.5 py-1.5 dark:border-teal-800/80 dark:bg-teal-950/50">
                        <span className="text-base font-bold tabular-nums text-teal-950 dark:text-teal-50">
                          ${Number(s.guest_price ?? 0).toFixed(2)}
                        </span>
                        <span className="text-xs font-semibold uppercase tracking-wide text-teal-800 dark:text-teal-200">
                          Guest
                        </span>
                      </span>
                      <span className="inline-flex items-center rounded-lg border border-stone-200 bg-stone-50 px-2.5 py-1.5 text-xs font-medium text-stone-700 dark:border-stone-700 dark:bg-stone-800 dark:text-stone-300">
                        Members: {creditsRequired} class pass
                      </span>
                    </div>
                  </div>
                </div>
                {/* Spots badge */}
                <span className={`mt-0.5 shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${
                  spotsLeft === 0
                    ? "bg-red-50 text-red-600 dark:bg-red-950/40 dark:text-red-400"
                    : spotsLow
                      ? "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300"
                      : "bg-teal-50 text-teal-700 dark:bg-teal-950/40 dark:text-teal-300"
                }`}>
                  {spotsLeft === 0
                    ? sessionCapacity > 0
                      ? `Full · 0 / ${sessionCapacity}`
                      : "Full"
                    : sessionCapacity > 0
                      ? `${spotsLeft} / ${sessionCapacity} spots left`
                      : spotsLow
                        ? `${spotsLeft} spots left`
                        : `${spotsLeft} spots`}
                </span>
              </div>

              {/* Actions */}
              <div className="mt-4 border-t border-stone-100 pt-3 dark:border-stone-800">
                {spotsLeft === 0 ? (
                  <span className={`text-sm ${ui.muted}`}>This class is full</span>
                ) : user ? (
                  <div className="flex flex-wrap gap-2">
                    <PackageBookButton sessionId={s.id} packages={userPacks} session={sessionCreditCtx} />
                    <BookButton sessionId={s.id} disabled={!paynow.configured} />
                    {!hasEligiblePack && userPacks.length > 0 ? (
                      <span className="text-xs text-amber-700 dark:text-amber-300">
                        Package not eligible for this class
                      </span>
                    ) : null}
                  </div>
                ) : (
                  <QuickBookPanel
                    slug={studioPublicSlug}
                    sessionId={s.id}
                    disabled={!paynow.configured}
                    triggerClassName={ui.btnSecondarySm}
                    triggerLabel="Book as guest"
                  />
                )}
              </div>
            </li>
          );
        })}
      </ul>
      {!listSessions.length ? (
        <div className={`mt-6 max-w-2xl ${ui.emptyState}`}>
          <p className={`text-sm ${ui.muted}`}>
            {isSessionShareView
              ? "This session is not available for booking anymore."
              : "No upcoming sessions yet. Check back soon."}
          </p>
        </div>
      ) : null}
    </main>
  );
}
