import Link from "next/link";
import { notFound } from "next/navigation";
import { BookButton } from "@/components/BookButton";
import { PackageBookButton } from "@/components/PackageBookButton";
import { QuickBookPanel } from "@/components/QuickBookPanel";
import { mergeGuestRecordsForUser } from "@/lib/guestMerge";
import {
  hasEligiblePackageForSession,
  sumCreditsInStudio,
  type MemberPackageForCredits,
} from "@/lib/memberCredits";
import { getPaynowSummary } from "@/lib/paynow";
import { normalizeStudioSlug } from "@/lib/slug";
import { ui } from "@/lib/ui";
import { createClient } from "@/lib/supabase/server";
import { z } from "zod";

type Props = {
  params: Promise<{ studioSlug: string; classSlug: string }>;
  searchParams: Promise<{ session_id?: string; session?: string }>;
};

export default async function PublicClassBookingPage({ params, searchParams }: Props) {
  const { studioSlug: rawStudio, classSlug: rawClass } = await params;
  const sp = await searchParams;
  const studioSlug = normalizeStudioSlug(rawStudio ?? "");
  const classSlug = String(rawClass ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!studioSlug || !/^[a-z0-9-]{6,80}$/.test(classSlug)) notFound();

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { data: studio } = await supabase
    .from("studios")
    .select(
      "id, name, public_slug, contract_status, paynow_enabled, paynow_proxy_type, paynow_uen, paynow_mobile, paynow_payee_name",
    )
    .eq("public_slug", studioSlug)
    .maybeSingle();
  if (!studio || studio.contract_status === "suspended") notFound();

  const { data: cls } = await supabase
    .from("classes")
    .select("id, title, description, studio_id, is_active, locations ( name )")
    .eq("studio_id", studio.id)
    .eq("share_slug", classSlug)
    .maybeSingle();
  if (!cls || cls.is_active === false) notFound();

  // Resolve requestedSessionId from either ?session=<slug> or ?session_id=<uuid>.
  // Share links generated by the dashboard use the slug form; direct links (e.g.
  // from ops tools) may still use the raw UUID form – both are accepted.
  let requestedSessionId: string | null = null;
  if (sp.session && /^[a-z0-9-]{6,80}$/.test(sp.session)) {
    const { data: bySlug } = await supabase
      .from("class_sessions")
      .select("id")
      .eq("class_id", cls.id)
      .eq("share_slug", sp.session)
      .maybeSingle();
    requestedSessionId = bySlug?.id ?? null;
  } else if (z.string().uuid().safeParse(sp.session_id ?? "").success) {
    requestedSessionId = String(sp.session_id);
  }

  let userPacks: MemberPackageForCredits[] = [];
  let packCredits = 0;
  if (user) {
    await mergeGuestRecordsForUser(user.id, user.email);
    const { data: packs } = await supabase
      .from("client_packages")
      .select("id, credits_left, expiry_date, packages!inner(name, studio_id, location_id)")
      .eq("client_id", user.id)
      .eq("packages.studio_id", studio.id)
      .gt("credits_left", 0)
      .or(`expiry_date.is.null,expiry_date.gt.${new Date().toISOString()}`);
    userPacks = ((packs ?? []) as {
      id: string;
      credits_left: number;
      expiry_date: string | null;
      packages?: { name?: string; studio_id?: string; location_id?: string | null } | null;
    }[]).map((p) => {
      const pkg = Array.isArray(p.packages) ? p.packages[0] : p.packages;
      return {
        id: p.id,
        name: pkg?.name ?? "Package",
        credits_left: p.credits_left,
        expiry_date: p.expiry_date,
        studio_id: pkg?.studio_id ?? studio.id,
        location_id: pkg?.location_id ?? null,
      };
    });
    packCredits = sumCreditsInStudio(userPacks, studio.id);
  }

  const { data: sessions } = await supabase
    .from("class_sessions")
    .select("id, start_time, spots_left, guest_price, credits_required, status, location_id")
    .eq("class_id", cls.id)
    .eq("status", "scheduled")
    .gte("start_time", new Date().toISOString())
    .order("start_time", { ascending: true });
  const orderedSessions = [...(sessions ?? [])].sort((a, b) => {
    if (!requestedSessionId) return 0;
    if (a.id === requestedSessionId) return -1;
    if (b.id === requestedSessionId) return 1;
    return 0;
  });

  const paynow = getPaynowSummary({
    paynow_enabled: Boolean(studio.paynow_enabled),
    paynow_proxy_type: studio.paynow_proxy_type ?? null,
    paynow_uen: studio.paynow_uen ?? null,
    paynow_mobile: studio.paynow_mobile ?? null,
    paynow_payee_name: studio.paynow_payee_name ?? null,
  });

  const loc = cls.locations as { name?: string } | { name?: string }[] | null;
  const locName = Array.isArray(loc) ? loc[0]?.name : loc?.name;

  return (
    <main className={ui.page}>
      {/* ── Class header ── */}
      <div className="max-w-2xl">
        <p className={ui.badge}>Shared class</p>
        <h1 className={`${ui.h1} mt-3`}>{cls.title}</h1>
        {cls.description ? (
          <p className={`mt-3 whitespace-pre-wrap text-stone-700 dark:text-stone-300`}>{cls.description}</p>
        ) : null}
        <p className={`mt-3 text-sm ${ui.muted}`}>
          {studio.name}{locName ? ` · ${locName}` : ""}
        </p>

        {/* Credits / sign-in nudge */}
        {user ? (
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <span className={ui.badge}>{packCredits} credit{packCredits !== 1 ? "s" : ""} available</span>
            <Link href="/checkout" className={`text-sm ${ui.link}`}>Buy more →</Link>
          </div>
        ) : (
          <p className={`mt-3 text-sm ${ui.muted}`}>
            <Link href="/auth" className={ui.link}>Sign in</Link>{" "}
            to book with credits, or book as a guest below.
          </p>
        )}

        {!paynow.configured ? (
          <p className={`mt-2 flex items-center gap-1 text-xs ${ui.error}`}>{paynow.line}</p>
        ) : null}
      </div>

      {/* ── Sessions ── */}
      <h2 className={`${ui.h2} mt-10`}>Upcoming sessions</h2>
      <ul className="mt-4 flex max-w-2xl flex-col gap-4">
        {orderedSessions.map((s) => {
          const start = new Date(s.start_time).toLocaleString();
          const creditsRequired = Number(s.credits_required ?? 1);
          const sessionCreditCtx = {
            studio_id: studio.id,
            location_id: s.location_id ?? null,
            credits_required: creditsRequired,
          };
          const hasEligiblePack = hasEligiblePackageForSession(userPacks, sessionCreditCtx);
          const spotsLeft = Number(s.spots_left ?? 0);
          const spotsLow = spotsLeft > 0 && spotsLeft <= 3;
          return (
            <li
              key={s.id}
              className={`${ui.card} ${requestedSessionId === s.id ? "ring-2 ring-teal-400/70" : ""}`}
            >
              {/* Info */}
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div className="min-w-0 flex-1">
                  <p className={`text-sm font-medium ${ui.muted}`}>{start}</p>
                  <div className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-stone-500 dark:text-stone-400">
                    <span>${Number(s.guest_price ?? 0).toFixed(2)} guest</span>
                    <span>{creditsRequired} credit{creditsRequired !== 1 ? "s" : ""} member</span>
                  </div>
                </div>
                <span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${
                  spotsLeft === 0
                    ? "bg-red-50 text-red-600 dark:bg-red-950/40 dark:text-red-400"
                    : spotsLow
                      ? "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300"
                      : "bg-teal-50 text-teal-700 dark:bg-teal-950/40 dark:text-teal-300"
                }`}>
                  {spotsLeft === 0 ? "Full" : `${spotsLeft} left`}
                </span>
              </div>

              {/* Actions */}
              <div className="mt-3 border-t border-stone-100 pt-3 dark:border-stone-800">
                {spotsLeft === 0 ? (
                  <span className={`text-sm ${ui.muted}`}>Class full</span>
                ) : user ? (
                  <div className="flex flex-wrap gap-2">
                    <PackageBookButton sessionId={s.id} packages={userPacks} session={sessionCreditCtx} />
                    <BookButton sessionId={s.id} disabled={!paynow.configured} />
                    {!hasEligiblePack && userPacks.length > 0 ? (
                      <span className="text-xs text-amber-700 dark:text-amber-300">
                        Package not eligible for this class
                      </span>
                    ) : null}
                  </div>
                ) : (
                  <QuickBookPanel slug={studioSlug} sessionId={s.id} disabled={!paynow.configured} />
                )}
              </div>
            </li>
          );
        })}
      </ul>
      {!orderedSessions.length ? (
        <div className={`mt-6 max-w-2xl ${ui.emptyState}`}>
          <p className={`text-sm ${ui.muted}`}>No upcoming sessions yet. Check back soon.</p>
        </div>
      ) : null}
    </main>
  );
}
