"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChevronRight, Search } from "lucide-react";
import { ui } from "@/lib/ui";

type Role = "owner" | "manager" | "frontdesk" | "instructor";
type HelpArticle = { title: string; summary: string; category: string; roles: Role[]; href: string; actionLabel: string; keywords: string[]; steps: string[]; note?: string };

const articles: HelpArticle[] = [
  { title: "Set up your studio", summary: "Create your studio, then add the information customers and staff need.", category: "Getting started", roles: ["owner"], href: "/dashboard/overview", actionLabel: "Open setup", keywords: ["new studio", "setup", "location", "service", "payment", "public page"], steps: ["Create the studio from Overview.", "In Settings, add locations, opening hours, staff, services, and payment details.", "Review the public profile before sharing its link with customers."] },
  { title: "Run the front desk", summary: "Use one workflow from customer arrival through checkout and end-of-shift cash handling.", category: "Daily operations", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/operations", actionLabel: "Open front desk", keywords: ["front desk", "walk in", "arrival", "check in", "checkout", "daily"], steps: ["Find or create the customer before starting work.", "Create or update the appointment, then check the customer in when they arrive.", "Take payment in POS and close the cash session at the end of the shift."] },
  { title: "Manage appointments", summary: "Find a booking, update its status, and check the customer in.", category: "Daily operations", roles: ["owner", "manager", "frontdesk", "instructor"], href: "/dashboard/appointments", actionLabel: "Open appointments", keywords: ["booking", "appointment", "check in", "customer", "cancel", "reschedule"], steps: ["Use the date and location filters to find the appointment.", "Open the appointment and confirm the customer, service, staff member, and time.", "Update the status as the customer arrives, is served, or cancels."] },
  { title: "Set staff availability and booking resources", summary: "Prevent booking conflicts by maintaining working hours, exceptions, and room or equipment availability.", category: "Daily operations", roles: ["owner", "manager"], href: "/dashboard/settings/booking?tab=staff", actionLabel: "Open staff schedules", keywords: ["availability", "working hours", "leave", "exception", "resource", "room", "equipment", "booking conflict"], steps: ["Select the correct location before editing weekly staff working hours.", "Add a dated exception when a person is unavailable instead of changing their normal week for one day.", "Review the Resources tab in Online booking for rooms, beds, or equipment before publishing services that require them."] },
  { title: "Take a POS payment", summary: "Create a sale, select the customer and payment method, then issue the receipt.", category: "Payments & exceptions", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/pos", actionLabel: "Open POS", keywords: ["pos", "sale", "cash", "card", "hitpay", "receipt", "checkout"], steps: ["Start a sale and add the service, product, package, or membership.", "Confirm the customer and total before selecting cash or HitPay.", "Complete payment only once, then open the sale history to view or send the receipt."] },
  { title: "Close a cash session", summary: "Open and close a shift cash session, check the expected amount, and record a difference.", category: "Payments & exceptions", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/pos/runbook", actionLabel: "Open cash guide", keywords: ["cash", "shift", "float", "till", "close", "difference", "short"], steps: ["Open a cash session before collecting cash.", "At shift end, enter the counted cash and review the calculated difference.", "Record a note and ask a manager to review any difference."] },
  { title: "Resolve a pending payment", summary: "Confirm a HitPay payment, sync it once, and know when to escalate an issue.", category: "Payments & exceptions", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/payments/runbook", actionLabel: "Open payment guide", keywords: ["pending", "payment", "hitpay", "paid", "sync", "money"], steps: ["Match the payment amount and reference with the customer’s proof of payment.", "Use Sync HitPay once and wait for the result.", "Escalate after the guided retries instead of creating another payment."] },
  { title: "Refund, void, and send receipts", summary: "Handle a completed sale carefully and leave a clear record for the team.", category: "Payments & exceptions", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/payments", actionLabel: "Open payments", keywords: ["refund", "void", "receipt", "invoice", "cancel sale", "credit note"], steps: ["Find the original payment or POS sale before taking action.", "Use the available refund or void action only after confirming the original payment and reason.", "Send or preview the invoice from the completed sale when the customer needs a receipt."], note: "Do not create a second payment to correct a pending or disputed charge." },
  { title: "Use packages and memberships", summary: "Sell, apply, and explain packages and memberships without confusing their benefits.", category: "Packages & memberships", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/packages", actionLabel: "Open packages", keywords: ["package", "membership", "credits", "balance", "expiry", "use package"], steps: ["Use Packages for a fixed number of credits with an expiry date.", "Use Memberships for recurring access or billing, according to the product’s terms.", "Check the customer profile before applying either benefit to a booking or sale."] },
  { title: "Manage membership products and subscribers", summary: "Set up recurring products and handle a subscriber’s lifecycle from one page.", category: "Packages & memberships", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/memberships", actionLabel: "Open memberships", keywords: ["membership", "subscriber", "subscription", "trial", "cancel membership", "recurring"], steps: ["Owners and managers create or edit membership products and their trial terms.", "Use the Subscribers tab to check active, paused, or ending subscriptions.", "Before cancelling, confirm the customer and the requested end date with them."], note: "Front desk can view and share membership links, but cannot change product settings." },
  { title: "Adjust package balances safely", summary: "Request an adjustment and complete the approval flow before changing customer credit.", category: "Packages & memberships", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/packages/approvals", actionLabel: "Open approvals", keywords: ["adjustment", "approval", "package balance", "credit", "expired", "correction"], steps: ["Open the customer’s package and verify the ledger before requesting a change.", "State the reason and amount clearly in the request.", "Wait for the required approval before treating the balance as changed."] },
  { title: "Manage classes, events, and shop items", summary: "Publish what customers can book, attend, or buy from the public studio page.", category: "Business management", roles: ["owner", "manager"], href: "/dashboard/schedule", actionLabel: "Open class sessions", keywords: ["class", "session", "event", "shop", "product", "publish", "schedule"], steps: ["Create and schedule class sessions with the right capacity and location.", "Use Events for time-bound activities and Shop for retail products.", "Check the public studio page after publishing to confirm customers can see the item."] },
  { title: "Follow up with customers", summary: "Use customer history, notes, and follow-ups to make the next contact useful.", category: "Business management", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/clients", actionLabel: "Open customers", keywords: ["customer", "client", "profile", "history", "follow up", "notes", "crm"], steps: ["Search for the customer before creating a duplicate profile.", "Review appointments, purchases, and notes in the customer profile.", "Record a clear next step and due date in the follow-up list."] },
  { title: "Handle customer information safely", summary: "Use only the customer details needed for their booking or service, and record consent correctly.", category: "Business management", roles: ["owner", "manager", "frontdesk"], href: "/dashboard/clients", actionLabel: "Open customers", keywords: ["privacy", "consent", "health", "allergy", "customer data", "anonymise"], steps: ["Confirm you have opened the correct customer before reading or changing their record.", "Record only information relevant to the service and follow the consent prompts on the profile.", "Escalate data-access, correction, or deletion requests to the designated owner instead of deleting records informally."] },
  { title: "Send marketing and read reports", summary: "Prepare a campaign carefully, then use reports to assess business performance.", category: "Business management", roles: ["owner", "manager"], href: "/dashboard/marketing", actionLabel: "Open marketing", keywords: ["marketing", "email", "campaign", "report", "sales", "revenue", "export"], steps: ["Check the audience and message before sending a campaign.", "Use Reports to review sales, customers, packages, and payroll information.", "Export only the data needed for the task and store it securely."] },
  { title: "Send a consent-safe email campaign", summary: "Test the message, confirm its audience, and schedule in Singapore time before sending.", category: "Business management", roles: ["owner", "manager"], href: "/dashboard/marketing", actionLabel: "Open marketing", keywords: ["email campaign", "test email", "schedule email", "consent", "audience", "delivery"], steps: ["Create the audience and draft, then verify the recipient count and consent basis.", "Send a test email and check links, subject line, sender name, and formatting.", "Send now or schedule in Singapore time, then review delivery results before repeating the campaign."] },
  { title: "Configure HitPay checkout", summary: "Set up the studio’s merchant payment settings without exposing credentials to staff or customers.", category: "Business management", roles: ["owner"], href: "/dashboard/settings/payments", actionLabel: "Open payment settings", keywords: ["hitpay", "merchant", "api key", "webhook", "checkout", "payment settings"], steps: ["Use the studio’s own HitPay merchant credentials, not a shared key from another studio.", "Confirm that checkout is enabled and both the API key and webhook salt show as configured.", "Run a controlled payment check before sharing payment-enabled links with customers."] },
  { title: "Manage staff access", summary: "Invite staff and give each person the minimum dashboard access they need.", category: "Staff & payroll", roles: ["owner"], href: "/dashboard/staff", actionLabel: "Open staff", keywords: ["staff", "employee", "invite", "role", "access", "permission"], steps: ["Invite the staff member using their work email address.", "Choose the role that matches their day-to-day responsibilities.", "Review access when a person changes role or leaves the studio."] },
  { title: "Set an employee’s payroll profile", summary: "Keep pay, statutory, and effective-date details complete before creating a payroll run.", category: "Staff & payroll", roles: ["owner"], href: "/dashboard/payroll", actionLabel: "Open payroll", keywords: ["payroll", "salary", "cpf", "sdl", "employee", "profile", "finalise blocker"], steps: ["Open the employee from Payroll and read any Finalise blockers first.", "Save a new profile version with the correct effective date, pay details, and statutory information.", "Do not overwrite a past period; use the effective date for a future change."] },
  { title: "Run payroll and issue payslips", summary: "Create a monthly draft, review every employee, then finalise and record payment.", category: "Staff & payroll", roles: ["owner"], href: "/dashboard/payroll", actionLabel: "Open payroll", keywords: ["payroll", "commission", "payslip", "salary", "pay run", "draft", "finalise", "paid"], steps: ["Create the monthly draft and review the employee count, gross pay, net pay, CPF, and SDL.", "Correct employee inputs or blockers, recalculate, and review the employee lines before Finalise.", "Finalise locks the month and publishes payslips; record Paid only after payment has actually been made."], note: "Only studio owners can manage payroll. Do not use Finalise as a draft approval step." },
  { title: "Correct a payroll run or payslip", summary: "Use the run status to decide whether you can edit, void, or download the relevant record.", category: "Staff & payroll", roles: ["owner"], href: "/dashboard/payroll", actionLabel: "Open payroll", keywords: ["void payroll", "correct payroll", "payslip", "recalculate", "mistake", "error"], steps: ["For a draft, update inputs and use Recalculate before Finalise.", "For a completed run, review the run status and reason before using the available Void action.", "Open the employee’s payslip only after finalisation; download the PDF when a copy is required."], note: "A finalised payroll period is locked. Preserve the reason for any void or correction." },
  { title: "Use payroll reports", summary: "Review published payroll and commission figures, then export only what is needed.", category: "Staff & payroll", roles: ["owner"], href: "/dashboard/payroll/reports", actionLabel: "Open payroll reports", keywords: ["payroll report", "commission report", "export", "published run"], steps: ["Choose the reporting period after the relevant run is published.", "Use the Payroll Summary for totals and the Commission Report for commission review.", "Keep exports restricted to authorised recipients because they contain employee pay data."] },
  { title: "View your appointments and pay", summary: "See your upcoming schedule and access your own pay information.", category: "Staff & payroll", roles: ["instructor"], href: "/dashboard/appointments", actionLabel: "Open appointments", keywords: ["instructor", "schedule", "my pay", "payslip", "appointment"], steps: ["Review upcoming appointments from the schedule.", "Keep appointment status accurate as work is completed.", "Open My pay to view your own pay information when it is available."] },
];

const roleLabels: Record<Role, string> = { owner: "Owner", manager: "Manager", frontdesk: "Front desk", instructor: "Instructor" };
function articleHref(href: string, search: string) { return search ? `${href}${href.includes("?") ? "&" : "?"}${search}` : href; }
function articleTopic(article: HelpArticle) { return article.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

export function HelpCenter({ role, search, topic }: { role: Role; search: string; topic?: string }) {
  const [query, setQuery] = useState("");
  const visibleArticles = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    return articles.filter((article) => article.roles.includes(role) && (!normalized || [article.title, article.summary, article.category, ...article.keywords, ...article.steps].join(" ").toLowerCase().includes(normalized)));
  }, [query, role]);
  const categories = [...new Set(visibleArticles.map((article) => article.category))];
  useEffect(() => {
    const article = topic ? articles.find((item) => articleTopic(item) === topic) : null;
    if (!article) return;
    const target = [...document.querySelectorAll<HTMLDetailsElement>("details")].find((element) => element.querySelector("summary")?.textContent?.includes(article.title));
    if (!target) return;
    target.open = true;
    target.scrollIntoView({ block: "center" });
  }, [topic]);
  return <div className="mx-auto flex w-full max-w-4xl flex-col gap-6"><div><h1 className={ui.h1}>Help</h1><p className={ui.muted}>Search for a task, read the short guide, then continue to the correct screen.</p></div><label className="relative block"><span className="sr-only">Search help</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-stone-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search help, for example: refund, cash, booking" className={`${ui.input} pl-10`} /></label>{visibleArticles.length > 0 ? <div className="flex flex-col gap-6">{categories.map((category) => <section key={category} aria-labelledby={`help-${category.replaceAll(" ", "-")}`}><h2 id={`help-${category.replaceAll(" ", "-")}`} className={ui.h2}>{category}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{visibleArticles.filter((article) => article.category === category).map((article) => <details key={article.title} className="group rounded-2xl border border-stone-200 bg-white p-4 shadow-sm dark:border-stone-800 dark:bg-stone-900"><summary className="flex cursor-pointer list-none gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-teal-50 text-teal-700 dark:bg-teal-950/40 dark:text-teal-300"><BookOpen size={17} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-1 text-sm font-semibold text-stone-900 dark:text-stone-100">{article.title}<ChevronRight size={15} className="transition-transform group-open:rotate-90" /></span><span className="mt-1 block text-xs leading-relaxed text-stone-500 dark:text-stone-400">{article.summary}</span><span className="mt-2 block text-[11px] font-medium text-teal-700 dark:text-teal-300">For {article.roles.map((articleRole) => roleLabels[articleRole]).join(", ")}</span></span></summary><ol className="mt-4 list-decimal space-y-1.5 pl-5 text-sm leading-relaxed text-stone-700 dark:text-stone-300">{article.steps.map((step) => <li key={step}>{step}</li>)}</ol>{article.note ? <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs leading-relaxed text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{article.note}</p> : null}<Link href={articleHref(article.href, search)} className={`${ui.btnSecondarySm} mt-4 w-fit`}>{article.actionLabel}<ChevronRight size={15} /></Link></details>)}</div></section>)}</div> : <div className={ui.card}><h2 className={ui.h2}>No matching guide yet</h2><p className={`mt-1 text-sm ${ui.muted}`}>Try a task name, screen name, or a word such as payment, booking, or customer.</p></div>}</div>;
}
